create database javajms;
use javajms;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE USERS (
    USERNAME NVARCHAR(128) PRIMARY KEY,
    PASSWORD NVARCHAR(128) NOT NULL,
    ENABLED CHAR(1) CHECK (ENABLED IN ('Y','N') ) NOT NULL
);


-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE AUTHORITIES (
    USERNAME NVARCHAR(128) NOT NULL,
    AUTHORITY NVARCHAR(128) NOT NULL
);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (USERNAME, AUTHORITY);
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ;

insert ignore into users values('gautam',"pass01", "Y");
insert ignore into authorities values('gautam','write');